import { FilterMatchMode, FilterOperator } from "primereact/api";
import { ColumnMeta } from "../../utils/Interfaces";
import { DataTableFilterMeta } from "primereact/datatable";
import { EmpresaEntity} from "../interfaces/EmpresaInterface";

export const columns: ColumnMeta[] = [
  {
    field: "IdEmpresa",
    header: "IdEmpresa",
    dataType: "numeric",
    width: "5%",
    show: true,
    filterPlaceholder: "Buscar por IdEmpresa",
  },
  {
    field: "Descripcion",
    header: "Descripcion",
    dataType: "text",
    width: "30%",
    show: true,
    filterPlaceholder: "Buscar por Descripcion",
  },
   {field:"NroIdentificacion",
    header: "NroIdentificacion",
    dataType: "text",
    width: "10%",   
    show: true,
    filterPlaceholder: "Buscar por NroIdentificacion",  
  },
  {
    field: "Email",
    filterField: "Email",
    header: "Email",
    dataType: "text",
    width: "20%",
    show: true,
    filterPlaceholder: "Buscar por Email",
  },
  {
    field: "Celular",
    filterField: "Celular",
    header: "Celular",
    dataType: "text",
    width: "10%",
    show: true,
    filterPlaceholder: "Buscar por Celular",
  },
{
    field: "RazonSocial",
    filterField: "RazonSocial",
    header: "RazonSocial",
    dataType: "text",
    width: "5%",
    show: false,
    filterPlaceholder: "Buscar por Razon Social",
  },
  {
    field: "UrlBase",
    filterField: "UrlBase",
    header: "UrlBase",
    dataType: "text",
    width: "20%",
    show: false,
    filterPlaceholder: "Buscar por Url Base",
  },
  {
    field: "FormatoLogo",
    filterField: "FormatoLogo",
    header: "FormatoLogo",
    dataType: "text",
    width: "5%",
    show: true,
    filterPlaceholder: "Buscar por Formato Logo",
  },
    {
    field: "NombreLogo",
    filterField: "NombretoLogo",
    header: "NombretoLogo",
    dataType: "text",
    width: "10%",
    show: true,
    filterPlaceholder: "Buscar por Nombre Logo",
  },
  {
    field: "SizeLogo",
    filterField: "SizeLogo",
    header: "SizeLogo",
    dataType: "numeric",
    width: "10%",
    show: false,
    filterPlaceholder: "Buscar por Size Logo",
  },
  {
    field: "UrlLogo",
    filterField: "UrlLogo",
    header: "UrlLogo",
    dataType: "text",
    width: "20%",
    show: true,
    filterPlaceholder: "Buscar por Url Logo",
  },
  {
    field: "Activo",
    header: "Activo",
    dataType: "boolean",
    width: "5%",
    show: true,
    filterPlaceholder: "Buscar por Activo",
  },
  {
    field: "CreadoEl",
    header: "CreadoEl",
    dataType: "date",
    width: "15%",
    show: false,
    filterPlaceholder: "Buscar por CreadoEl",
  },
  {
    field: "CreadoPor",
    header: "CreadoPor",
    dataType: "text",
    width: "10%",
    show: false,
    filterPlaceholder: "Buscar por CreadoPor",
  },
  {
    field: "ModificadoEl",
    header: "ModificadoEl",
    dataType: "date",
    width: "15%",
    show: false,
    filterPlaceholder: "Buscar por ModificadoEl ",
  },
  {
    field: "ModificadoPor",
    header: "ModificadoPor",
    dataType: "text",
    width: "10%",
    show: false,
    filterPlaceholder: "Buscar por ModificadoPor ",
  },
];

export const defaultFilters: DataTableFilterMeta = {
  global: { value: null, matchMode: FilterMatchMode.CONTAINS },

  IdEmpresa: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }],
  },
  Descripcion: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }],
  },
  NroIdentificacion: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }],
  },
  Email: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }],
  },
  Celular: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }],
  },
  RazonSocial: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }],
  },
  UrlBase: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }],
  },
  FormatoLogo: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }],
  },
  NombreLogo: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }],
  },
  SizeLogo: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }],
  },
  UrlLogo: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }],
  },
  Activo: { value: null, matchMode: FilterMatchMode.EQUALS },
  CreadoEl: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.DATE_IS }],
  },
  CreadoPor: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }],
  },
  ModificadoEl: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.DATE_IS }],
  },
  ModificadoPor: {
    operator: FilterOperator.AND,
    constraints: [{ value: null, matchMode: FilterMatchMode.EQUALS }],
  },
};

export let emptyEmpresa: EmpresaEntity = {
  IdEmpresa: 0,
  Descripcion: "",
  NroIdentificacion: "",
  Email: "",
  Celular: "",
  RazonSocial: "",
  // UrlBase: "",
  // FormatoLogo: "",
  // NombreLogo: "",
  // SizeLogo: 0,
  // UrlLogo: "",
  LogoNombre: "",
  LogoBase64: "",
  Activo: true,
  CreadoEl: new Date(),
  CreadoPor: "",
  ModificadoEl: new Date() ,
  ModificadoPor: "",
};
